version: '3.7'

services:
  minio1:
    image: minio/minio:RELEASE.2021-01-08T21-18-21Z
    volumes:
      - data1:/data1
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  api:
    build: .
    environment:
      MINIO_URL: http://minio:9000/
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - "8080:8080"

volumes:
  data1: