minio:
  accesskey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
  endpointUrl: ${MINIO_URL}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
